### ISSUE TITLE
MDK crashes VS 2017 during deploy.

### ISSUE THREAD

**Issue by kwilliams1987** [malware-dev/MDK-SE#123]
The addon kept crashing Visual Studio when I was deploying my project: 
https://github.com/kwilliams1987/SE-ShipSystemsManager/tree/convert-to-state-machine

I was have trouble figuring out why, so I ran the debug mode from the MDK-SE master and got the following during deploy:

```
Reference of type 'Microsoft.CodeAnalysis.UnresolvedMetadataReference' is not valid for this compilation.
Parameter name: references[0]
   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonWithReferences(IEnumerable`1 newReferences)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.UpdateCompilationWithNewReferencesAndRecordAssemblySymbols(Compilation compilation, List`1 newReferences, Dictionary`2 metadataReferenceToProjectId)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
```

It appears to happen during the call to `void ProjectDependentCommand.TryGetValidProject(out Project project, out ProjectScriptInfo projectInfo)` at line 21 of DeployProjectCommand.cs.

Any ideas?

**Comment by malware-dev** [comment]
None. Seems like it's not finding a reference of sorts? You'll have to dig a little deeper...

**Comment by kwilliams1987** [comment]
Managed to fix the issue by copying my code to a new project and comparing.
Seems I had a reference to the development project of MDKUtilities instead of a DLL reference to the MDKUtilities.dll from the extension.

Heres the commit to my code that fixed it: https://github.com/kwilliams1987/SE-ShipSystemsManager/commit/60722f6077c4b25c7852055f66fe5f02d32baab6

Sorry for wasting your time. 🙃

**Comment by malware-dev** [comment]
No worries 😃
