### ISSUE TITLE
[PRE] Error upgrading project

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#127]
System.Runtime.InteropServices.COMException (0x80004005): Project unavailable.
   at EnvDTE.Project.get_UniqueName()
   at Malware.MDKServices.DTEExtensions.Unload(Project project)
   at MDK.Views.ProjectHealth.ProjectHealthDialogModel.<RunUpgrades>d__31.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Views\ProjectHealth\ProjectHealthDialogModel.cs:line 150

**Comment by malware-dev** [comment]
May I please have the failing project?

**Comment by Wicorel** [comment]
Project is here:
https://github.com/Wicorel/WicoSpaceEngineers/tree/master/MDK%20Craft%20Control

You'll need to get a lot of that tree as they are sub-projects.
