### ISSUE TITLE
Failure to update an existing project

### ISSUE THREAD

**Issue by LambdaSix** [malware-dev/MDK-SE#183]
"The following MDK projects must be upgraded in order to function correctly.

Athena
  :( Missing paths file
  :( Missing Whitelist cache
"

Attempting to repair results in:

`Malware.MDKServices.MDKProjectPropertiesException: An error occurred while attempting to save project information to C:\Users\somervn\source\repos\Personal\SpaceEngineers\Athena\src\mdk\mdk.paths.props. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XElement.set_Value(String value)
   at Malware.MDKServices.MDKProjectPaths.Save()
   --- End of inner exception stack trace ---
   at Malware.MDKServices.MDKProjectPaths.Save()
   at MDK.Views.ProjectHealth.Fixes.MissingPathsFileFix.Apply(HealthAnalysis analysis, FixStatus status) in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Views\ProjectHealth\Fixes\MissingPathsFileFix.cs:line 22
   at MDK.Views.ProjectHealth.ProjectHealthDialogModel.<>c__DisplayClass31_1.<RunUpgrades>b__1() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Views\ProjectHealth\ProjectHealthDialogModel.cs:line 157
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Views.ProjectHealth.ProjectHealthDialogModel.<RunUpgrades>d__31.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Views\ProjectHealth\ProjectHealthDialogModel.cs:line 157`

**Comment by malware-dev** [comment]
Could you please provide an STR?

**Comment by LambdaSix** [comment]
A what now?

**Comment by jeffdesouzadev** [comment]
I think this is the place it is asking for me to paste the error log?

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCProjectShim'.
   at Microsoft.Verify.NotDisposed(Boolean condition, Object disposedValue, String message)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCProjectShim.get_ProjectFile()
   at EnvDTE.Project.get_FullName()
   at Malware.MDKServices.DTEExtensions.IsLoaded(Project project)
   at Malware.MDKServices.HealthAnalysis.Analyze(Project project, HealthAnalysisOptions options)
   at Malware.MDKServices.HealthAnalysis.<>c__DisplayClass1_1.<AnalyzeAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<OnSolutionLoaded>d__42.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 202
