### ISSUE TITLE
Error during MDK Deploy

### ISSUE THREAD

**Issue by jturp** [malware-dev/MDK-SE#200]
MDK.Build.BuildException: Error writing final script for C:\Users\Public\OneDrive\Documents\Production Manager\ProductionManager\ProductionManager\ProductionManager.csproj ---> System.IO.IOException: The cloud operation was unsuccessful.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at MDK.Build.BuildModule.WriteScript(Project project, String output, String script) in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 207
   --- End of inner exception stack trace ---
   at MDK.Build.BuildModule.WriteScript(Project project, String output, String script) in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 219
   at MDK.Build.BuildModule.<BuildAsync>d__27.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<DeployAsync>d__47.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 359

**Comment by malware-dev** [comment]
This is a OneDrive error and beyond my control. Sorry.
