### ISSUE TITLE
OutOfMemoryException on deploy

### ISSUE THREAD

**Issue by Stridemann** [malware-dev/MDK-SE#217]
MDK v1.2.32

VisualStudio 2019 Pro. v16.7.0 (Launched as x32 bit)
Permanent exception while deploy. Had to restart VS each time.

devenv.exe:
using 2.773.348 Kb RAM, working set: 2.960.808 Kb (from Process explorer)
On startup devenv.exe is using 900 MB of RAM. Increasing after each deploy by ~100mb
Looks like memory leak. Maybe need to dispose something..?

Have 45GB of RAM free.

`MDK.Build.BuildException: Error loading script projects from D:\HomeProjects\Games\SpaceEngineers\GameScripts\SpaceEngineersSolution.sln ---> System.OutOfMemoryException: Недостаточно памяти для продолжения выполнения программы.
   at System.Runtime.InteropServices.Marshal.AllocHGlobal(IntPtr cb)
   at System.Reflection.Internal.NativeHeapMemoryBlock.DisposableData..ctor(Int32 size)
   at System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(Stream stream, Boolean isFileStream, Int64 start, Int32 size)
   at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options, Int32 size)
   at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.Host.MetadataServiceFactory.Service.<>c__DisplayClass1_0.<.ctor>b__0(String path, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.Host.MetadataReferenceCache.ReferenceSet.GetAddOrUpdate(String path, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.Host.MetadataReferenceCache.GetReference(String path, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.Host.MetadataServiceFactory.Service.GetReference(String resolvedPath, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.Host.WorkspaceMetadataFileReferenceResolver.ResolveReference(String reference, String baseFilePath, MetadataReferenceProperties properties)
   at Microsoft.CodeAnalysis.CommandLineArguments.ResolveMetadataReference(CommandLineReference cmdReference, MetadataReferenceResolver metadataResolver, List`1 diagnosticsOpt, CommonMessageProvider messageProviderOpt)
   at Microsoft.CodeAnalysis.CommandLineArguments.ResolveMetadataReferences(MetadataReferenceResolver metadataResolver, List`1 diagnosticsOpt, CommonMessageProvider messageProviderOpt, List`1 resolved)
   at Microsoft.CodeAnalysis.CommandLineArguments.ResolveMetadataReferences(MetadataReferenceResolver metadataResolver)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<ResolveReferencesAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<>c__DisplayClass21_0.<<CreateProjectInfoAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<DoOperationAndReportProgressAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadSolutionInfoAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<LoadScriptProjectsAsync>d__26.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 131
   --- End of inner exception stack trace ---
   at MDK.Build.BuildModule.<LoadScriptProjectsAsync>d__26.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<DeployAsync>d__47.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 359`

**Comment by malware-dev** [comment]
You'll need to give me a reproduction project.

**Comment by Stridemann** [comment]
> You'll need to give me a reproduction project.
How to find you in discord? I lost MDK discord server link and cannot find it anymore..

**Comment by malware-dev** [comment]
There's no MDK discord. You'll find me on Keen's.
