### ISSUE TITLE
Error while deploying: 'System.ArgumentNullException: Value cannot be null.'

### ISSUE THREAD

**Issue by Argual** [malware-dev/MDK-SE#228]
I got this error while deploying my script.
I did it without minifying.
The error only occurs when I enable the unused type removing.

~~I suspect that this is the offending source: https://pastebin.com/H9e8hjzm~~
This is the script: https://pastebin.com/yZ14YigT

~~I did not paste all files as the issue is only present since I have been working on the "offending source" mentioned before.~~

EDIT: It seems that the problem was that I have been using aliases for types.

`System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MDK.Build.TypeTrimming.TypeTrimmer.<ProcessAsync>d__4.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\TypeTrimming\TypeTrimmer.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<BuildAsync>d__27.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<DeployAsync>d__47.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 359`

**Comment by malware-dev** [comment]
Sorry this took so long...


Well, using aliases won't work for an ingame script anyway, as they cannot be translated to any form the PB will understand.
