### ISSUE TITLE
Visual Studio Enterprise is unsupported

### ISSUE THREAD

**Issue by vrelk** [malware-dev/MDK-SE#242]
I have Visual Studio Enterprise 2019 (education license), but the installer only seems to accept Community edition. Unless there are some other requirements for enterprise, could you make that an acceptable product to use this with?

```
Space Engineers is trademarked to Keen Software House. This toolkit is fan-made, and its developer has no relation to Keen Software House.
6/20/2021 6:45:48 PM - 	Locale             : en-US
6/20/2021 6:45:48 PM - 	MoreInfoURL        : https://github.com/malware-dev/MDK-SE
6/20/2021 6:45:48 PM - 	InstalledByMSI     : False
6/20/2021 6:45:48 PM - 	SupportedFrameworkVersionRange : [4.6.1,)
6/20/2021 6:45:48 PM - 
6/20/2021 6:45:48 PM - 	SignatureState     : Unsigned
6/20/2021 6:45:48 PM - 	Supported Products : 
6/20/2021 6:45:48 PM - 		Microsoft.VisualStudio.Community
6/20/2021 6:45:48 PM - 			Version : [16.8,17.0)
6/20/2021 6:45:48 PM - 
6/20/2021 6:45:48 PM - 	References         : 
6/20/2021 6:45:48 PM - 	Prerequisites      : 
6/20/2021 6:45:48 PM - 		-------------------------------------------------------
6/20/2021 6:45:48 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/20/2021 6:45:48 PM - 		Name         : Visual Studio core editor
6/20/2021 6:45:48 PM - 		Version      : [15.0,)
6/20/2021 6:45:48 PM - 
6/20/2021 6:45:48 PM - 		-------------------------------------------------------
6/20/2021 6:45:48 PM - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
6/20/2021 6:45:48 PM - 		Name         : Roslyn Language Services
6/20/2021 6:45:48 PM - 		Version      : [15.0,)
6/20/2021 6:45:48 PM - 
6/20/2021 6:45:48 PM - Signature Details...
6/20/2021 6:45:48 PM - 	Extension is not signed.
6/20/2021 6:45:48 PM - 
6/20/2021 6:45:48 PM - Searching for applicable products...
6/20/2021 6:45:48 PM - Found installed product - Global Location
6/20/2021 6:45:48 PM - Found installed product - Visual Studio Enterprise 2019
6/20/2021 6:45:48 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by OnuxNemori** [comment]
I am using visual studio enterprise (also educational license), near clean install, works fine for me. Might be a different issue?
(Using latest MDK version)

**Comment by malware-dev** [comment]
Do you have at least 16.8? Having 2019 isn't enough, you need an updated version of it.

**Comment by vrelk** [comment]
> 
> 
> Do you have at least 16.8? Having 2019 isn't enough, you need an updated version of it.

That may have been it as I am on 16.9.1 now. I ran it again today, and it worked. I don't think it updated since I ran it last, but I did update between two install attempts last time. Either way, it is working now.
