### ISSUE TITLE
Crash on startup of VS 16.11.2

### ISSUE THREAD

**Issue by mtwombley** [malware-dev/MDK-SE#245]
Just updated VS and this happened on startup.

System.Runtime.InteropServices.COMException (0x8001010A): The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER))
   at EnvDTE.Project.get_FullName()
   at Malware.MDKServices.DTEExtensions.IsLoaded(Project project)
   at Malware.MDKServices.HealthAnalysis.Analyze(Project project, HealthAnalysisOptions options)
   at Malware.MDKServices.HealthAnalysis.<>c__DisplayClass1_1.<AnalyzeAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<OnSolutionLoaded>d__42.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 209

**Comment by malware-dev** [comment]
Thank you for the report and sorry for the late response. I have not yet had a chance to test this and I fear it will still be a few days until I get a chance. If I have not responded by monday, ping me again.

**Comment by malware-dev** [comment]
Hm. I cannot seem to reproduce this. Do you have steps to reproduce?

**Comment by mtwombley** [comment]
I just opened an MDK project and it was working fine. So I can't reproduce
it either. I say close it and call it okay.
Thanks
