### ISSUE TITLE
Crash: "an unexpected error occurred during the attempt to analyze the solution"

### ISSUE THREAD

**Issue by exo-pla-net** [malware-dev/MDK-SE#275]
System.NullReferenceException: Object reference not set to an instance of an object.
   at Malware.MDKServices.HealthAnalysis.GetProjects(IEnumerable`1 projects)
   at Malware.MDKServices.HealthAnalysis.GetProjects(IEnumerable`1 projects)
   at Malware.MDKServices.HealthAnalysis.AnalyzeAsync(Solution solution, HealthAnalysisOptions options)
   at MDK.MDKPackage.<OnSolutionLoaded>d__42.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 209

**Comment by exo-pla-net** [comment]
Notes:
- Happened immediately when I loaded my .sln.
- There's nothing SpaceEngineers related on my D:\ drive, so I'm not sure where the MoveNext() error is coming from.
- The crash was resolved when I made a new Solution and copied the contents of my Projects over.

**Comment by malware-dev** [comment]
Strange - what is different with that solution? And that's from the MDK source and has nothing to do with anything _you_ have 🙂

**Comment by exo-pla-net** [comment]
It could have been solar radiation that corrupted a bit somewhere in the .sln.

Only half-joking.

In the new solution, the only change was that I didn't select the "Trim" option for any of the Projects.

**Comment by exo-pla-net** [comment]
The same error has resurfaced in my new Solution:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Malware.MDKServices.HealthAnalysis.GetProjects(IEnumerable`1 projects)
   at Malware.MDKServices.HealthAnalysis.GetProjects(IEnumerable`1 projects)
   at Malware.MDKServices.HealthAnalysis.AnalyzeAsync(Solution solution, HealthAnalysisOptions options)
   at MDK.MDKPackage.<OnSolutionLoaded>d__42.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 209
```

**Comment by exo-pla-net** [comment]
Once again, making a new solution and copy-pasting the contents of all of my _.cs_ files into new projects fixed the error/crashing.

**Comment by malware-dev** [comment]
Next time, please upload the failing project.

**Comment by malware-dev** [comment]
Since I haven't received any failing projects again I'll assume this is no longer a problem.
