### ISSUE TITLE
MDK.Build.BuildException: Error writing final script

### ISSUE THREAD

**Issue by jturp** [malware-dev/MDK-SE#289]
When attempting to deploy a script with the latest version, the below error occurs. I do not have the thumb opened or in use by any other program.

```
MDK.Build.BuildException: Error writing final script for C:\Users\...\OneDrive\Documents\HoverScript\HoverScript\HoverScript.csproj ---> System.IO.IOException: The process cannot access the file 'C:\Users\...\OneDrive\Documents\HoverScript\HoverScript\thumb.png' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at MDK.Build.BuildModule.WriteScript(Project project, String output, String script) in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 212
   --- End of inner exception stack trace ---
   at MDK.Build.BuildModule.WriteScript(Project project, String output, String script) in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 220
   at MDK.Build.BuildModule.<BuildAsync>d__27.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<DeployAsync>d__47.MoveNext() in D:\Repos\SpaceEngineers\MDK-SE\Source\MDK\MDKPackage.cs:line 366
```

**Comment by jturp** [comment]
Nevermind this. I had set the deploy path to the working directory.
