### ISSUE TITLE
Crash on "Copy to Clipboard"

### ISSUE THREAD

**Issue by tgkgate** [malware-dev/MDK-SE#295]
VS2022 restarts whenever I use Copy to Clipboard after doing a script deployment.

This is repeatable regardless of which MDK project I have open,  only occurs in 2022.

MDK version as of 2023/05/01

**Comment by malware-dev** [comment]
I am going to need the log.

**Comment by malware-dev** [comment]
https://learn.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2022

**Comment by tgkgate** [comment]
[ActivityLog.zip](https://github.com/malware-dev/MDK-SE/files/11377351/ActivityLog.zip)

Here ya go.

**Comment by malware-dev** [comment]
Thank you! It's a bit too late today but I will have a look tomorrow.

**Comment by tgkgate** [comment]
Actions taken:

Launched VS2022 w/ /log as a parameter.
Waited for it to settle. 
Opened solution containing MDK project
Deployed Project
Clicked "Copy to Clipboard"
VS Closed and Reopened

**Comment by malware-dev** [comment]
Of course there is _nothing_ in that log that even _mentions_ MDK. What about Windows event viewer?

**Comment by tgkgate** [comment]
Event Viewer -> Applications and Service Logs -> Visual Studio : 0 Events Logged.

However,  Under Custom Views -> Admin Events:

Source Application Error

```
Faulting application name: devenv.exe, version: 17.5.33627.172, time stamp: 0x644ad283
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2788, time stamp: 0x62e593d6
Exception code: 0xe0434352
Fault offset: 0x000000000002cb69
Faulting process id: 0x37e0
Faulting application start time: 0x01d97d31ef6c73b1
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: b01bb688-8cb5-40a8-84f0-fde76510821c
Faulting package full name: 
Faulting package-relative application ID: 
```

Source .NET Runtime
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at MDK.VisualStudio.NotificationBar+<ShowAsync>d__30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at MDK.Views.DeploymentBar.DeploymentBar+<CopyLink_OnClicked>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

**Comment by malware-dev** [comment]
That is a _little bit_ helpful. Points me to the point of failure at least. Thanks!

**Comment by malware-dev** [comment]
Try it now.

**Comment by tgkgate** [comment]
Appears to function as expected now.   Text was copied to clipboard,  and VS didn't crash.

Thanks.

- Closing
