### ISSUE TITLE
Cannot create new project D:

### ISSUE THREAD

**Issue by Scavenjer** [malware-dev/MDK-SE#41]
System.Runtime.InteropServices.COMException (0x80004005): Project unavailable.
   at EnvDTE.Project.Save(String FileName)
   at Malware.MDKServices.ScriptUpgrades.AnalyzeProject(Project project, ScriptUpgradeAnalysisOptions options)
   at Malware.MDKServices.ScriptUpgrades.<>c__DisplayClass13_0.<AnalyzeAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Malware.MDKServices.ScriptUpgrades.<AnalyzeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<OnSolutionLoaded>d__48.MoveNext() in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 260

Tried creating a new project while another windows of VS was open, got this

**Comment by malware-dev** [comment]
I wasn't able to reproduce this problem, but I can make an educated guess on what's happening. It doesn't really have anything to do with having another VS open. It's about VS being really unclear on telling me when a project or solution is ready to be analyzed, so I suspect somehow the analyzer was being run multiple times, and was actually unloaded at this time. I will keep searching for a way to deal with this.

**Comment by malware-dev** [comment]
Given our discussion on Discord I think I will close this for now, until it happens again and we can find some way to reproduce it. In the mean time, the educated guess above is still in the back of my mind and I will probably do something about _that_ regardless.
