### ISSUE TITLE
Issue starting VS2017 Pro after MDK 1.3 install

### ISSUE THREAD

**Issue by sysigy** [malware-dev/MDK-SE#43]
I've installed the latest MDK but after opening a project in VS2017 (not an MDK project) I get the following error from VS...

![mdk_1 3_error](https://user-images.githubusercontent.com/31881853/30315181-fb7b99b0-979a-11e7-9a3a-7562045fd0fb.png)

`System.NotImplementedException: The method or operation is not implemented.
   at EnvDTE.Project.Save(String FileName)
   at Malware.MDKServices.ScriptUpgrades.AnalyzeProject(Project project, ScriptUpgradeAnalysisOptions options)
   at Malware.MDKServices.ScriptUpgrades.<>c__DisplayClass13_0.<AnalyzeAsync>b__1()
   at System.Threading.Tasks.Task'1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Malware.MDKServices.ScriptUpgrades.<AnalyzeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<OnSolutionLoaded>d__48.MoveNext() in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 260`

**Comment by malware-dev** [comment]
Hm, that's strange. I haven't seen this problem myself. I will investigate.

**Comment by malware-dev** [comment]
I really hope this will fix your problem. As I can't reproduce it myself I can only make an educated guess on what went wrong and why.

**Comment by sysigy** [comment]
Visual Studio had a pending update this morning (UK time) which brought the version up to VS2017 Pro  15.3.4, I also updated to the latest MDK version and then opened a non MDK project to try to reproduce the above error (which happened every time I tried this)... problem solved.  No error.

Will update if I see the error again but initial tests seems to indicate you have fixed it.

**Comment by malware-dev** [comment]
Glad to hear it!
