### ISSUE TITLE
Oh Noez (deploying minified script).

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#45]
As requested, here is the log. Will also attempt repro.

MDK.Build.BuildException: Error loading script projects from C:\Users\saett\OneDrive\Documents\Visual Studio 2017\Projects\MDK Nav\MDK Nav.sln ---> System.InvalidOperationException: The operation cannot be completed because a build is already in progress.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Execution.BuildManager.BeginBuild(BuildParameters parameters)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.BuildAsync(BuildManager buildManager, BuildParameters parameters, BuildRequestData requestData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.<BuildAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.ProjectFile.<BuildAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.CSharp.CSharpProjectFileLoader.CSharpProjectFile.<GetProjectFileInfoAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadProjectAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<GetOrLoadProjectAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadSolutionInfoAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<LoadScriptProjects>d__30.MoveNext() in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 116
   --- End of inner exception stack trace ---
   at MDK.Build.BuildModule.<LoadScriptProjects>d__30.MoveNext() in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<<Run>b__29_0>d.MoveNext() in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MDK.MDKPackage.<Deploy>d__49.MoveNext() in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 359

**Comment by Wicorel** [comment]
Deploy again and no crash.  Didn't close/open/etc anything except this page.

**Comment by malware-dev** [comment]
Thanks. I see what is going on, the service is trying to start a compilation process while a compilation is already underway.

**Comment by malware-dev** [comment]
You don't happen to remember exactly what you did? I know that's a difficult question, but, you know... Every little bit helps...

**Comment by malware-dev** [comment]
I'm so sorry these things take so long, it will happen, I promise...

**Comment by malware-dev** [comment]
Since the build system is under a massive rewrite, including the minifier, this issue is no longer relevant.
