### ISSUE TITLE
Crash when analyzing solution

### ISSUE THREAD

**Issue by theCalcaholic** [malware-dev/MDK-SE#53]
When loading my solution in VS I get the following error with the notice: 'An unexpected error occured during the attempt to analyze the solution. MDK has been disabled to prevent further crashes.'

I'm currently using v1.0.11

```System.ArgumentNullException: Value cannot be null.
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at Malware.MDKServices.ProjectScriptInfo.GetActualGameBinPath(String defaultPath)
   at Malware.MDKServices.ScriptUpgrades.AnalyzeProject(Project project, ScriptUpgradeAnalysisOptions options)
   at Malware.MDKServices.ScriptUpgrades.<>c__DisplayClass13_0.<AnalyzeAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Malware.MDKServices.ScriptUpgrades.<AnalyzeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.MDKPackage.<OnSolutionLoaded>d__48.MoveNext() in C:\Users\Morten\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 260
```

**Comment by malware-dev** [comment]
It is somehow unable to retrieve Space Engineers' binary folder. It should tell you this rather than just crash. Do you have SE installed?

**Comment by theCalcaholic** [comment]
I do, MDK is set to automatically figure out the installation path. I'll try setting it explicitly.

**Comment by theCalcaholic** [comment]
I have good news! I think it's not a bug (at least not with MDK). Steam apparently *forgot* where I had installed Space Engineers...

**Comment by malware-dev** [comment]
That is good news indeed! I'd still call it a bug though, although far less important: It still shouldn't _crash_ in this situation, just tell you what's wrong. But at least now I don't need to rush to fix it 😛
