### ISSUE TITLE
[pre] Crash when deploying with minification

### ISSUE THREAD

**Issue by Wicorel** [malware-dev/MDK-SE#60]
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis.Workspaces, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.CodeAnalysis.Workspaces, Version=2.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at MDK.Build.BuildModule.<RunAsync>b__25_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MDK.MDKPackage.<DeployAsync>d__49.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 359

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

---

This is first-time I tried.  I will continue to test to get more details.

**Comment by Wicorel** [comment]
Also happens with a second project.

**Comment by malware-dev** [comment]
Have you made sure you have the most updated Visual Studio?

**Comment by Wicorel** [comment]
Updating to 15.6.4 now.  Then will retest.

**Comment by Wicorel** [comment]
Fixed with update to VS version.

**Comment by malware-dev** [comment]
Thank you, good to hear
