### ISSUE TITLE
NullReferenceException during Deploy

### ISSUE THREAD

**Issue by baratgabor** [malware-dev/MDK-SE#64]
Exception when deploying. Unused type trimming is on. Minifying is off.

**I can confirm that it's related to the type trimming, because in another solution Deploy was working fine, but after turning on the trimming, it started to throw identical exceptions.**

I don't have `E:\Dropbox\Projects...` btw. :)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at MDK.Build.AnalysisExtensions.<>c__DisplayClass0_0.<IsInterfaceImplementation>b__1(ISymbol member) in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\AnalysisExtensions.cs:line 26
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at MDK.Build.AnalysisExtensions.IsInterfaceImplementation(ISymbol symbol) in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\AnalysisExtensions.cs:line 26
   at MDK.Build.UsageAnalysis.SymbolAnalyzer.IsNotSpecialDefinitions(SymbolDefinitionInfo s) in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\UsageAnalysis\SymbolAnalyzer.cs:line 15
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at MDK.Build.UsageAnalysis.SymbolAnalyzer.FindSymbols(ProgramComposition composition, ProjectScriptInfo config) in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\UsageAnalysis\SymbolAnalyzer.cs:line 35
   at MDK.Build.UsageAnalysis.UsageAnalyzer.<FindUsagesAsync>d__1.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\UsageAnalysis\UsageAnalyzer.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.TypeTrimming.TypeTrimmer.<ProcessAsync>d__0.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\TypeTrimming\TypeTrimmer.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<BuildAsync>d__27.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MDK.MDKPackage.<DeployAsync>d__49.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 359``
```

**Comment by malware-dev** [comment]
Please provide the (or _a_) script project that causes the exception. If I cannot reproduce, I cannot fix 🙂

**Comment by baratgabor** [comment]
I'm attaching here the smallest project that triggered the exception. The solution has a shared project in it, but I've included that as well in the zip, so hopefully it will be usable. But let me know if I should provide it in some other way instead. 🙂

[repos.zip](https://github.com/malware-dev/MDK-SE/files/1895675/repos.zip)
