### ISSUE TITLE
Incompatible with Visual Studio 15.8?

### ISSUE THREAD

**Issue by malware-dev** [malware-dev/MDK-SE#80]
User reported crash which indicates this.

**Comment by sirhamsteralot** [comment]
```System.TypeLoadException: Kan type Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace niet laden vanuit assembly Microsoft.CodeAnalysis.Workspaces.Desktop, Version=2.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
   at MDK.Build.BuildModule.<LoadScriptProjectsAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at MDK.Build.BuildModule.LoadScriptProjectsAsync()
   at MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MDK.MDKPackage.<DeployAsync>d__50.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 367```

**Comment by sirhamsteralot** [comment]
happens on deploy, my deploy settings: 
![image](https://user-images.githubusercontent.com/24956361/44147535-cc2df2ee-a094-11e8-9daf-bf89f8ddc01f.png)

**Comment by malware-dev** [comment]
### MDK is currently NOT compatible with VS 15.8 since they haven't released a nuget package with the applicable Roslyn yet.

**Comment by malware-dev** [comment]
An emergency prerelease specifically for VS 15.8 has been released.

**Comment by malware-dev** [comment]
MS has finally released what I'm hoping is the right Roslyn version. If so a new stable MDK version will be released tonight.

**Comment by malware-dev** [comment]
Ok... Yes, they're released the right Roslyn version, but there's a type missing there. Gotta wait a little longer then.

**Comment by malware-dev** [comment]
Finally they released everything needed. The latest version should be compatible with the newest VS version now. Unfortunately it also _requires_ said version, but that's par for the course, unfortunately.
