### ISSUE TITLE
Crash on deploy

### ISSUE THREAD

**Issue by theCalcaholic** [malware-dev/MDK-SE#82]
With the latest mdk version, I get the following exception when deploying my project. Not sure what information could help you in this case, please let me know :)

VS version: 15.7.6
```cs
MDK.Build.BuildException: Error loading script projects from F:\informatics\PowertruckChargingScript\PowertruckChargingScript.sln ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.MSBuildMefHostServices.get_DefaultServices()
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create()
   at MDK.Build.BuildModule.<LoadScriptProjectsAsync>d__26.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 0
   --- End of inner exception stack trace ---
   at MDK.Build.BuildModule.<LoadScriptProjectsAsync>d__26.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MDK.Build.BuildModule.<<RunAsync>b__25_0>d.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\Build\BuildModule.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at MDK.MDKPackage.<DeployAsync>d__50.MoveNext() in E:\Dropbox\Projects\Space Engineers\MDK-SE\Source\MDK\MDKPackage.cs:line 367
```

**Comment by theCalcaholic** [comment]
Closed, because probably caused by an outdated version of VS
